apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EWNameReferenceCheck
metadata:
  name: configmap-not-referenced
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ConfigMap"]
  parameters:
    sameNamespace: true
    operations: ["DELETE"]
    resources:
      - apiGroup: apps
        version: v1
        kind: Deployment
        nameFields:
          - spec.template.spec.volumes.configMap.name
          - spec.template.spec.containers.envFrom.configMapRef.name
