---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EWExpressionCheckCELProtectedDelete
metadata:
  name: block-delete-of-earlywatch-protected-object
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ConfigMap"]
