apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EWExistingResourcesField
metadata:
  name: service-must-have-no-matching-pods
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
  parameters:
    operations: ["DELETE"]
