apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EWBlockDeleteCriticalInProd
metadata:
  name: block-delete-critical-in-prod
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ConfigMap"]
