apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EWBlockDeleteInProduction
metadata:
  name: block-delete-in-production-namespace
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ConfigMap"]
